# -*- coding: utf-8 -*-
"""Text Mining assignment 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ReDy1MWFr0ld_Gz33FYgD-gHvoPIJ-1D
"""

from google.colab import files
file = files.upload()

import pandas as pd

# Try reading the CSV file with different encodings
try:
    files = pd.read_csv('Elon_musk.csv', encoding='utf-8')
except UnicodeDecodeError:
    files = pd.read_csv('Elon_musk.csv', encoding='latin1')

# Display the first few rows of the DataFrame
files.head()

# prompt: Perform sentimental analysis on the Elon-musk tweets (Exlon-musk.csv)

import pandas as pd
from textblob import TextBlob

# Create a new column for the sentiment
files['Sentiment'] = files['Text'].apply(lambda x: TextBlob(x).sentiment.polarity)

# Display the first few rows of the DataFrame
files.head()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

# Create a TF-IDF vectorizer
vectorizer = TfidfVectorizer(stop_words='english')

# Fit the vectorizer to the text data
X = vectorizer.fit_transform(files['Text'])

# Create a KMeans model with 5 clusters
km = KMeans(n_clusters=5)

# Fit the KMeans model to the TF-IDF vectors
km.fit(X)

# Add the cluster labels to the DataFrame
files['Cluster'] = km.labels_

# Print the cluster labels
print(files['Cluster'])